import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { AppKit } from "../../context/appkit";
import ContractProvider from "./contract-provider";
import type { Metadata } from "next";
import Navbar from "@/components/layout/navbar";
import { NextUIProviders } from "./provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppKit>
          <ContractProvider>
            <NextUIProviders>
              <Toaster />
              <Navbar />
              <main className="mt-32">{children}</main>
            </NextUIProviders>
          </ContractProvider>
        </AppKit>
      </body>
    </html>
  );
}
